package com.ved.framework.entity;

public interface InputType {
    int TYPE_CLASS_PHONE = 28;
    int TYPE_DATETIME_VARIATION_DATE = 30;
    int TYPE_DATETIME_VARIATION_NORMAL = 29;
    int TYPE_DATETIME_VARIATION_TIME = 31;
    int TYPE_NULL = 0;
    int TYPE_NUMBER_FLAG_DECIMAL = 26;
    int TYPE_NUMBER_FLAG_SIGNED = 25;
    int TYPE_NUMBER_VARIATION_NORMAL = 24;
    int TYPE_NUMBER_VARIATION_PASSWORD = 27;
    int TYPE_TEXT_FLAG_AUTO_COMPLETE = 6;
    int TYPE_TEXT_FLAG_AUTO_CORRECT = 5;
    int TYPE_TEXT_FLAG_CAP_CHARACTERS = 2;
    int TYPE_TEXT_FLAG_CAP_SENTENCES = 4;
    int TYPE_TEXT_FLAG_CAP_WORDS = 3;
    int TYPE_TEXT_FLAG_IME_MULTI_LINE = 8;
    int TYPE_TEXT_FLAG_MULTI_LINE = 7;
    int TYPE_TEXT_FLAG_NO_SUGGESTIONS = 9;
    int TYPE_TEXT_VARIATION_EMAIL_ADDRESS = 11;
    int TYPE_TEXT_VARIATION_EMAIL_SUBJECT = 12;
    int TYPE_TEXT_VARIATION_FILTER = 20;
    int TYPE_TEXT_VARIATION_LONG_MESSAGE = 14;
    int TYPE_TEXT_VARIATION_NORMAL = 1;
    int TYPE_TEXT_VARIATION_PASSWORD = 17;
    int TYPE_TEXT_VARIATION_PERSON_NAME = 15;
    int TYPE_TEXT_VARIATION_PHONETIC = 21;
    int TYPE_TEXT_VARIATION_POSTAL_ADDRESS = 16;
    int TYPE_TEXT_VARIATION_SHORT_MESSAGE = 13;
    int TYPE_TEXT_VARIATION_URI = 10;
    int TYPE_TEXT_VARIATION_VISIBLE_PASSWORD = 18;
    int TYPE_TEXT_VARIATION_WEB_EDIT_TEXT = 19;
    int TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS = 22;
    int TYPE_TEXT_VARIATION_WEB_PASSWORD = 23;
}
